export const Barangay = [
  "Arena Blanco",
  "Ayala",
  "Baliwasan",
  "Baluno",
  "Barangay Zone I",
  "Barangay Zone II",
  "Barangay Zone III",
  "Barangay Zone IV",
  "Boalan",
  "Bolong",
  "Buenavista",
  "Bunguiao",
  "Busay (Sacol Island)",
  "Cabaluay",
  "Cabatangan",
  "Cacao",
  "Calabasa",
  "Calarian",
  "Camino Nuevo",
  "Campo Islam",
  "Canelar",
  "Capisan",
  "Cawit",
  "Culianan",
  "Curuan",
  "Divisoria",
  "Dulian (Upper Bunguiao)",
  "Dulian (Upper Pasonanca)",
  "Guisao",
  "Guiwan",
  "Kasanyangan",
  "La Paz",
  "Labuan",
  "Lamisahan",
  "Landang Gua",
  "Landang Laum",
  "Lanzones",
  "Lapakan",
  "Latuan",
  "Licomo",
  "Limaong",
  "Limpapa",
  "Lubigan",
  "Lumayang",
  "Lumbangan",
  "Lunzuran",
  "Maasin",
  "Malagutay",
  "Mampang",
  "Manalipa",
  "Mangusu",
  "Manicahan",
  "Mariki",
  "Mercedes",
  "Muti",
  "Pamucutan",
  "Pangapuyan",
  "Panubigan",
  "Pasilmanta",
  "Pasobolong",
  "Pasonanca",
  "Patalon",
  "Putik",
  "Quiniput",
  "Recodo",
  "Rio Hondo",
  "Salaan",
  "San Jose Cawa-cawa",
  "San Jose Gusu",
  "San Roque",
  "Sangali",
  "Santa Barbara",
  "Santa Catalina",
  "Santa Maria",
  "Santo Niño",
  "Sibulao",
  "Sinubung",
  "Sinunoc",
  "Tagasilay",
  "Taguiti",
  "Talabaan",
  "Talisayan",
  "Talon-talon",
  "Taluksangay",
  "Tetuan",
  "Tictapul",
  "Tigbalabag",
  "Tigtabon",
  "Tolosa",
  "Tugbungan",
  "Tulungatung",
  "Tumaga",
  "Tumalutab",
  "Tumitus",
  "Victoria",
  "Vitali",
  "Zambowood",
];
